#!/bin/bash

TARGET="/Users/anders/Dropbox/dotfilesbackup"

# Create folder if it does not exist
mkdir -p $TARGET

# Zshell
cp ~/.zshrc ${TARGET}/zshrc

# SSH
cp ~/.ssh/config ${TARGET}/ssh_config
# TODO - Copy keys

# Hosts
cp /etc/hosts ${TARGET}/hosts

# Apache
cp /etc/apache2/extra/httpd-vhosts.conf ${TARGET}/vhosts.conf

# Gitconfig
cp ~/.gitconfig ${TARGET}/gitconfig

# Sublime
cp "/Users/anders/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"  ${TARGET}/sublime_preferences
cp "/Users/anders/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap"  ${TARGET}/sublime_keymap
